const Map<String, String> en_US = {
  '是': 'Yes',
  '否': 'No',
  '取消': 'Cancel',
  '完成': 'Done',
  '確定': 'OK',
  '確認': 'Confirm',
  '提示': 'Notice',
  '不用': 'No',
  '不使用': 'No, don\'t use',
  '使用': 'Yes, use it',
  '檢測到上次未提交的填寫數據，是否使用？': 'Unsubmitted draft found. Use it to fill the form?',
  '保存': 'Save',
  '保存图片': 'Save Image',
  '刪除': 'Delete',
  '創建': 'Create',
  '下一步': 'Next',
  '上一步': 'Previous',

  /// 歡迎頁面
  '網絡連接失敗': 'Network connection failed',
  '重試': 'Retry',
  '路上有光，盟友相伴': 'LUMO Leads, Guide Exceeds',

  /// 登錄頁面
  '登錄': 'Log In',
  '登 錄': 'Log In',
  '請輸入郵箱': 'Enter Email',
  '請輸入密碼': 'Enter Password',
  '記住密碼': 'Remember Password',
  '忘記密碼': 'Forgot Password',
  '還沒有帳號? 去註冊': 'No account? Register now',
  '請輸入正確的郵箱': 'Enter a valid email address',
  '我已閲讀并同意': 'I have read and agree to',
  '《用戶協議》': ' The User Agreement ',
  '和': 'and',
  '《隱私政策》': ' The Privacy Policy ',
  '登錄成功': 'Log In successful',
  '請先閱讀並同意用戶協議和隱私政策':
      'Please read and agree to the User Agreement and Privacy Policy first',

  /// 註冊頁面
  '註冊': 'Register',
  '輸入您的電子郵箱': 'Enter your email',
  '使用您的郵箱註冊或登錄路盟': 'Use your email to register or log in to LuMo',
  '請輸入您的邀請碼': 'Enter your invitation code',
  '請輸入您的電子郵箱': 'Enter your email address',
  '註冊失敗': 'Registration failed',

  /// 密碼設置頁面
  '密碼設置': 'Set Password',
  '請輸入6~12位密碼，包含數字、字母':
      'Enter a 6-12 character password containing numbers and letters',
  '請重複密碼': 'Re-enter Password',
  '找回密碼': 'Reset Password',
  '密碼格式不正確，請輸入6~12位密碼，包含數字和字母':
      'Invalid password format. Enter a 6-12 character password containing numbers and letters',
  '請輸入確認密碼': 'Enter confirmation password',
  '兩次輸入密碼不一致': 'Passwords do not match',
  '註冊成功': 'Registration successful',
  '密碼重置成功': 'Password reset successful',
  '輸入註冊時填寫的電子郵箱': 'Enter the email address used during registration',
  '密碼修改成功': 'Password changed successfully',

  /// 驗證碼頁面
  '輸入驗證碼': 'Enter Verification Code',
  '已發送6位驗證碼至': 'A 6-digit verification code has been sent to',
  '重新獲取': 'Resend Code',
  '重新獲取(@s)秒': 'Resend (@s)s',
  '請輸入6位驗證碼': 'Enter the 6-digit verification code',
  '驗證中': 'Verifying',
  '發送中': 'Sending',
  '驗證碼已發送': 'Verification code sent',

  '首頁': 'Home',
  '消息': 'Messages',

  /// 首頁
  '請輸入城市名稱': 'Enter city name',
  '搜索': 'Search',
  '導遊': 'Guides',
  '遊客': 'Travelers',
  '餐廳': 'Restaurants',
  '購物': 'Shopping',
  '住宿': 'Accommodation',
  '票務': 'Tickets',
  '熱門城市': 'Popular Cities',
  '查看全部': 'View All',
  '在路上輕鬆掌握每個城市': 'Easily Explore Cities',
  '推薦導遊': 'Recommended Guides',
  '輕鬆找到專業導遊': 'Easily Find Professional Guides',
  '推薦商家': 'Recommended Businesses',
  '輕鬆找到合作商家': 'Easily Find Businesses Partner',
  '資訊': 'News',
  '及時瞭解當地咨詢': 'Stay Updated with Local Information',
  '城市地址': 'City Address',

  /// 資訊
  '資訊詳情': 'News Details',
  '評論': 'Comments',
  '查看更多': 'View More',
  '我來講兩句': 'Add a comment',
  '次瀏覽': 'views',

  /// 個人中心
  '我的': 'My',
  '關注': 'Following',
  '積分': 'Points',
  '粉絲': 'Followers',
  'ID': 'ID',
  '邀請碼': 'Invitation Code',

  '@d天免費試⽤': '@d days free trial',
  '繼續使⽤LuMo Guide的全部功能， \n請您使⽤積分兌換或付費延長會籍':
      'To continue using all features of LuMo Guide, please redeem points or pay to extend your membership.',
  '想繼續成為 LuMo 的合作商家嗎？\n⾺上延長會籍':
      'Want to remain a LuMo partner business?\n Extend your membership now.',
  '我的服务': 'My Services',
  'LuMoFun': 'LuMoFun',
  'Fun商城': 'Fun Store',
  '兌換紀錄': 'Redemption History',
  '邀請': 'Invitations',
  '我的預約': 'My Bookings',
  '預約我的': 'Bookings for Me',
  '發布': 'Posts',
  '認證資料': 'Verification Info',
  '商家管理': 'Business Management',
  '會員中心': 'Membership Center',
  '您是旅遊⾏業從業者嗎？您想獲得更多旅遊資訊及展⽰⾃⼰嗎? ⾺上成為 LuMo Guide':
      'Are you in the tourism industry? Want more travel info and to showcase yourself? Become a LuMo Guide now.',
  '您想增加遊客業務和旅遊合作嗎？您想更多展⽰⾃⼰嗎? 去成為 LuMo 的合作商家':
      'Want to increase tourist business and partnerships? Showcase yourself more? Become a LuMo partner business.',
  '瞭解更多': 'Learn More',
  '去加入': 'Join Now',
  '審核中': 'Under Review',
  '審核未通過': 'Review Failed',

  /// 修改資料
  '修改資料': 'Edit Profile',
  '頭像': 'Avatar',
  '暱稱': 'Nickname',
  '郵箱': 'Email',
  '手機號': 'Phone Number',
  '去綁定': 'Bind',
  '出生日期': 'Date of Birth',
  '修改暱稱': 'Edit Nickname',
  '暱稱最多10個字': 'Nickname up to 10 characters',
  '確 定': 'Confirm',
  '綁定手機號': 'Bind Phone Number',
  '請輸入手機號': 'Enter phone number',
  '請輸入短信驗證碼': 'Enter SMS verification code',
  '獲取驗證碼': 'Get Code',
  '選擇出生日期': 'Select Date of Birth',
  '驗證碼發送成功': 'Verification code sent successfully',
  '修改失敗': 'Update failed',
  '綁定成功': 'Binding successful',
  '提交成功': 'Submitted Successfully',

  /// 設置
  '設置': 'Settings',
  '語言切換': 'Language',
  '用戶協議': 'User Agreement',
  '隱私政策': 'Privacy Policy',
  '修改密碼': 'Change Password',
  '聯繫我們': 'Contact Us',
  '意見反饋': 'Feedback',
  '清除緩存': 'Clear Cache',
  '檢查更新': 'Check for Updates',
  '請輸入注册时填写的邮箱': 'Enter the email used during registration',
  '請輸入郵箱驗證碼': 'Enter email verification code',
  '請輸入新密碼': 'Enter new password',
  '請輸入標題': 'Enter title',
  '請輸入內容': 'Enter content',
  '在線留言': 'Online Message',
  '請將您遇到的問題/產品建議反饋給我們，建議您盡可能詳細地描述問題，便於我們幫您解決。':
      'Please provide feedback on any issues or product suggestions. Detailed descriptions help us assist you better.',
  '上傳圖片': 'Upload Image',
  '退出登錄': 'Log Out',
  '確定退出登錄嗎？': 'Are you sure you want to log out?',

  /// 城市
  '城市': 'Cities',
  '暫無城市數據': 'No city data available',
  '最近瀏覽的城市：': 'Recently Viewed Cities:',
  '推薦': 'Recommended',
  '全部': 'All',
  '首都': 'Capital',
  '城市詳情': 'City Details',
  '概覽': 'Overview',
  'LuMo\nGuide': 'LuMo\nGuide',
  '景點': 'Attractions',
  '交通': 'Transportation',
  '設施': 'Facilities',
  '活動': 'Events',
  '城市概覽': 'City Overview',
  '城市歷史': 'City History',
  '開放時間': 'Opening Hours',
  '門票': 'Tickets',
  '電話': 'Phone',
  '地址': 'Address',
  '關注成功': 'Followed successfully',
  '已取消關注': 'Unfollowed',

  /// 消息
  '我的評論': 'My Comments',
  '評論我的': 'Comments on Me',
  '我的關注': 'My Following',
  '關注我的': 'My Followers',
  '系統消息': 'System Messages',
  '掃一掃': 'Scan',
  '創建群組': 'Create Group',
  '创建群组失败': 'Create group failed',
  '我的群聊': 'My Groups',
  '群組詳情': 'Group Profile',
  '搜索聊天記錄': 'Search Chat',
  '成員數': 'Members',
  '群類型': 'Group Type',
  '群ID': 'Group ID',
  '公開群': 'Public',
  '工作群': 'Work',
  '會議群': 'Meeting',
  '直播群': 'AVChatRoom',
  '群聊': 'Group Chat',
  '与@X的群聊': 'Chat with @X',
  '等@N人': ' and @N others',
  '選擇好友': 'Select Members',
  '選擇成員': 'Select Members',
  '群二維碼': 'Group QR Code',
  '修改群名稱': 'Edit group name',
  '修改群頭像': 'Edit group avatar',
  '掃碼加入群聊': 'Scan to join group',
  '請使用手機掃描': 'Please use your phone to scan',
  '未識別到群二維碼': 'No group QR code detected',
  '未識別到二維碼': 'Unrecognized QR code',
  '群組不存在或已解散': 'Group does not exist or has been dismissed',
  '加入成功': 'Joined successfully',
  '加入失敗': 'Failed to join',
  '清空消息': 'Clear messages',
  '清空聊天記錄': 'Clear chat history',
  '退出群組': 'Leave group',
  '解散群組': 'Dismiss group',
  '退出後不會接收到此群聊消息':
      'You will not receive messages from this group after leaving',
  '解散後不會接收到此群聊消息':
      'You will not receive messages from this group after dismissing',
  '分享': 'Share',
  '已保存到相册': 'Saved to photos',
  '保存失败': 'Save failed',
  '加載失敗': 'Load failed',
  '圖片加載失敗': 'Image load failed',
  '暫無頭像': 'No avatar yet',
  '分享失败': 'Share failed',
  '添加': 'Add',
  '添加成員': 'Add Members',
  '添加成功': 'Added successfully',
  '添加群成员失败': 'Failed to add group members',
  '只有关注的您的人才可以被邀请': 'Only people who follow you can be invited',
  '關注信息': 'Follow Info',
  '評論信息': 'Comment Info',
  '預定信息': 'Booking Info',
  '消息詳情': 'Message Details',
  '查看詳情': 'View Details',
  '自定義消息': 'Custom Message',
  '圖片': 'Image',
  '視頻': 'Video',
  '語音': 'Voice',
  '文件': 'File',
  '表情': 'Emoji',

  /// 導遊詳情
  '導遊詳情': 'Guide Details',
  '本地導遊': 'Local Guide',
  '語  言': 'Language',
  '所在地': 'Location',
  '聯繫電話': 'Contact Phone',
  '郵箱地址': 'Email Address',
  '其他聯繫方式': 'Other Contact Info',
  '微信': 'WeChat',
  '可從事工作類型': 'Work Types',
  '是否有車輛資源': 'Vehicle Available',
  '車輛可否出租': 'Vehicle Rentable',
  '車輛圖片顯示': 'Vehicle Photos',
  '簡介': 'Introduction',
  '發消息': 'Send Message',
  '預約': 'Book',
  '已關注': 'Following',

  /// 商家詳情
  '店鋪詳情': 'Store Details',
  '營業時間': 'Business Hours',
  '餐廳可容納人數': 'Restaurant Capacity',
  '是否接受團餐預訂': 'Accepts Group Bookings',
  '網址': 'Website',
  '店鋪介紹': 'Store Introduction',
  '預約進店': 'Book a Visit',
  '開始時間': 'Start Time',
  '結束時間': 'End Time',
  '詳情介紹': 'Details',
  '本店特色': 'Store Features',
  '店舖介紹': 'Store Introduction',
  '交通介紹': 'Transportation Info',
  '歷史及介紹': 'History & Introduction',
  '預約參觀': 'Book a Tour',
  '預約詢價': 'Request a Quote',
  '景點預約': 'Attraction Booking',
  '餐廳預約': 'Restaurant Booking',
  '購物預約': 'Shopping Booking',
  '酒店預約': 'Hotel Booking',
  '票務預約': 'Ticket Booking',

  /// 評論
  '說點什麼吧～': 'Say something...',
  '景點評價': 'Attraction Review',
  '一般': 'Average',
  '好': 'Good',
  '極好': 'Excellent',
  '提交': 'Submit',
  '很差': 'Very Poor',
  '差': 'Poor',
  '請輸入評論': 'Enter a comment',
  '評論成功': 'Comment posted successfully',
  '資訊評論': 'News Comments',
  '全部評論': 'All Comments',

  /// 積分
  '我的積分': 'My Points',
  '積分規則': 'Points Rules',
  '當前積分': 'Current Points',
  '積分明細': 'Points Details',
  '去兌換': 'Redeem',
  '商品詳情': 'Product Details',
  '立即兌換': 'Redeem Now',
  '運費：': 'Shipping:',
  '包郵': 'Free Shipping',
  '不包郵': 'Shipping Fee Applies',
  '已兌換：': 'Redeemed:',
  '件': 'item(s)',
  '應付:': 'Payable:',
  '確定要兌換麼？': 'Confirm redemption?',
  '剩餘積分:': 'Remaining Points:',
  '兌換成功': 'Redemption successful',
  '確認兌換': 'Confirm Redemption',
  '收貨地址': 'Shipping Address',
  '收貨人': 'Recipient',
  '請輸入收貨人姓名': 'Enter recipient name',
  '請輸入聯繫電話': 'Enter contact phone number',
  '請輸入詳細地址': 'Enter detailed address',
  '請選擇收貨地址': 'Select a shipping address',
  '我的地址': 'My Addresses',
  '新增收貨地址': 'Add Shipping Address',
  '編輯': 'Edit',
  '默認': 'Default',
  '設為默認': 'Set as Default',
  '請輸入姓名': 'Enter name',
  '姓名': 'Name',
  '郵編': 'Postal Code',
  '請填寫郵編': 'Enter postal code',
  '詳細地址': 'Detailed Address',
  '請填寫詳細地址': 'Enter detailed address',
  '为了能確保收貨地址準確，請填寫詳細地址\n(國家/城市/街道)':
      'To ensure accurate delivery, please enter detailed address\n(Country/City/Street)',
  '新增地址': 'Add Address',
  '編輯地址': 'Edit Address',
  '暫無收貨地址': 'No shipping address yet',
  '保存成功': 'Saved Successfully',
  '選擇國家': 'Select Country',
  '確定要刪除當前地址麼？': 'Delete this address?',
  '刪除成功': 'Deleted Successfully',
  '刪除失敗': 'Delete Failed',
  '刪除會話': 'Delete Conversation',
  '確定要刪除此會話嗎？': 'Are you sure to delete this conversation?',
  '兌換時間: @time': 'Redemption time: @time',
  '訂單詳情': 'Order Details',
  '運費': 'Shipping Fee',
  '需付款/實付款': 'Amount Due/Paid',
  '訂單編號': 'Order Number',
  '下單時間': 'Order Time',
  '支付時間': 'Payment Time',
  '快遞名稱': 'Courier',
  '快遞單號': 'Tracking Number',
  '兌換成功，等待平台確認處理': 'Redemption successful, awaiting platform confirmation',
  '返回': 'Back',
  '查看訂單': 'View Order',

  /// 導遊認證
  'LuMo Guide': 'LuMo Guide',
  '基礎信息': 'Basic Info',
  '專業信息': 'Professional Info',
  '證件信息': 'Document Info',
  '確定提交': 'Confirm Submission',
  '上傳照片或logo': 'Upload Photo or Logo',
  '請上傳照片或logo': 'Upload a photo or logo',
  '請輸入真實姓名': 'Enter your real name',
  '請輸入郵箱地址': 'Enter Email address',
  '請輸入賬單地址': 'Enter billing address',
  '請輸入賬單地址(請輸入英文)': 'Enter billing address (in English)',
  '請輸入其他聯繫方式': 'Enter other contact info',
  '請輸入其他聯繫方式: Line、微信、WhatsApp 等':
      'Enter other contact info: Line, WeChat, WhatsApp, etc.',
  '例如: 微信: 賬號123456': 'E.g.: WeChat: account123456',
  '人像需正式照片，可能會在頁面中展示': 'Portrait should be a formal photo, may be displayed',
  '真實姓名': 'Real Name',
  '請輸入英文姓名/拼音': 'Enter English name/Pinyin',
  '英文姓名/拼音': 'English Name/Pinyin',
  '賬單地址': 'Billing Address',
  '您熟練掌握的語言': 'Languages You Master',
  '(可多選)': '(Multiple choices)',
  '請選擇語言': 'Select language(s)',
  '選擇語言': 'Select Language',
  '從業年份': 'Years in Profession',
  '請選擇從業年份': 'Select years in profession',
  '選擇從業年份': 'Select Years in Profession',
  '您邀請人的邀請碼': 'Your Inviter\'s Code',
  '從事旅遊行業的類型': 'Type of Tourism Work',
  '請輸入': 'Enter',
  '在APP中展示的身份類型': 'Display Role in App',
  '個人或公司簡介': 'Personal or Company Bio',
  '請輸入個人或公司簡介(比如經歷，專長，特色，擅長領域，收費標準等)':
      'Enter personal/company bio (e.g., experience, specialties, expertise, rates)',
  '業務聯繫人': 'Business Contact',
  '請輸入業務聯繫人': 'Enter business contact person',
  '車輛類型/數量': 'Vehicle Type/Quantity',
  '請輸入車輛類型和數量': 'Enter vehicle type and quantity',
  '例如: 五座車 (2輛)': 'E.g.: 5-seater (2 vehicles)',
  '專業資格證書圖片': 'Professional Certificate Images',
  '例如導遊證，國際領隊證，營業執照等':
      'E.g., guide license, international tour leader cert, business license',
  '護照證件圖片': 'Passport Image',
  '駕駛執照圖片': 'Driver\'s License Image',
  '正面': 'Front',
  '反面': 'Back',
  '車輛照片': 'Vehicle Photos',
  '最多可上傳5張': 'Up to 5 images',
  '拍照': 'Take Photo',
  '從相冊選擇': 'Choose from Album',
  'LuMo Guide 特權': 'LuMo Guide Privileges',
  '推廣您的業務，讓所有LuMo用戶找到您': 'Promote your business, let all LuMo users find you',
  '建立您的行業人脈': 'Build your industry network',
  '獲取LuMo Guide分享的所有一手資訊': 'Get all first-hand info shared by LuMo Guide',
  '在線聯絡 LuMo Guide 和合作商家': 'Contact LuMo Guides and partners online',
  '管理預訂': 'Manage Bookings',
  '分享行業相關信息和 Tips，獲得更多 LuMoFun':
      'Share industry info and tips, earn more LuMoFun',
  '想成為LuMo Guide 請點擊 "下一步"': 'To become a LuMo Guide, click "Next"',
  '開始上傳的您的身份信息': 'Start uploading your identity information',
  '請輸入從業年份': 'Enter years in profession',
  '請選擇展示身份類型': 'Select display role type',
  '請輸入簡介': 'Enter bio',
  '請輸入從業聯繫人': 'Enter professional contact person',
  '請選擇從業類型': 'Select type of work',
  '請輸入其他從業類型': 'Enter other work type',
  '請輸入車輛信息': 'Enter vehicle info',
  '請上傳證件照片': 'Upload document photos',
  '圖片選擇失敗': 'Image selection failed',
  '您熟練掌握的語言(可多選)': 'Languages You Master (Multiple choices)',
  '導遊認證資料提交成功': 'Guide verification submitted successfully',
  '企業入駐資料提交成功': 'Business registration submitted successfully',
  '請等待管理员审核~': 'Please wait for admin review~',
  '審核狀態': 'Review Status',
  '審核通過': 'Approved',

  /// 商家入駐
  '企業會員': 'Business Member',
  '商家類型': 'Business Type',
  '聯繫信息': 'Contact Info',
  '上傳照片': 'Upload Photos',
  '公司名稱': 'Company Name',
  '所在城市': 'City',
  '請輸入公司名稱': 'Enter company name',
  '請輸入英文公司名稱': 'Enter English company name',
  '英文公司名稱': 'English Company Name',
  '請選擇所在城市': 'Select city',
  '公司地址': 'Company Address',
  '請輸入公司地址': 'Enter company address',
  '公司稅號': 'Company Tax ID',
  '請輸入公司稅號': 'Enter company tax ID',
  '經營類型': 'Business Type',
  '請選擇企業經營類型': 'Select business type',
  '請輸入企業簡介': 'Enter company bio',
  '請輸入Email': 'Enter Email',
  '請輸入公司網站': 'Enter company website',
  '請輸入其他聯係方式：Line、微信、WhatsApp 等':
      'Enter other contacts: Line, WeChat, WhatsApp, etc.',
  '相關證件圖片': 'Relevant Certificate Images',
  '例如營業執照等': 'E.g., business license, etc.',
  '商家圖片': 'Business Photos',
  '請上傳商家照片，最多5張': 'Upload business photos, up to 5',
  '商家信息提交成功': 'Business info submitted successfully',
  '商家信息提交失敗': 'Business info submission failed',

  /// 發佈資訊
  '發佈資訊': 'Post News',
  '分類': 'Category',
  '請選擇資訊分類': 'Select news category',
  '資訊標題': 'News Title',
  '請輸入資訊標題': 'Enter news title',
  '資訊內容': 'News Content',
  '請輸入資訊內容': 'Enter news content',
  '資訊圖片': 'News Image',
  '只能上傳JPG/PNG文件,且不超過500KB': 'Only JPG/PNG files under 500KB',
  '選擇誰可見': 'Visibility',
  '僅 LuMo Guide': 'LuMo Guides Only',
  '所有人': 'Everyone',
  '確認發佈資訊': 'Confirm Post',
  '發布成功，請等待管理員審核~': 'Posted successfully, awaiting admin review~',
  '請上傳最少一張圖片': 'Upload at least one image',

  /// 發佈景點
  '歸屬城市': 'Belongs to City',
  '請選擇歸屬城市': 'Select city',
  '景點類型': 'Attraction Type',
  '請選擇景點類型': 'Select attraction type',
  '景點名稱': 'Attraction Name',
  '請輸入景點名稱': 'Enter attraction name',
  '請輸入開放時間': 'Enter opening hours',
  '票價': 'Ticket Price',
  '請輸入票价，可填寫單⼈，優惠票，團體票的信息':
      'Enter ticket prices (individual, concession, group)',
  '免費': 'Free',
  '收費': 'Paid Admission',
  '如何到達': 'How to Get There',
  '請輸入如何到達': 'Enter directions',
  '無可選城市': 'No cities available',
  '官方網站': 'Official Website',
  '請輸入官方網站': 'Enter official website',
  '請輸入地址': 'Enter address',
  '相關介紹': 'Related Introduction',
  '請輸入相關介紹': 'Enter related introduction',
  '景點圖片': 'Attraction Images',

  /// 發佈設施
  '所屬城市': 'City',
  '請選擇所屬城市': 'Select city',
  '設施名稱': 'Facility Name',
  '請輸入設施名稱': 'Enter facility name',
  '設施介紹': 'Facility Introduction',
  '請輸入設施介紹': 'Enter facility introduction',
  '設施圖片': 'Facility Images',
  '確認發佈設施': 'Confirm Post Facility',

  /// 發佈活動
  '活動類型': 'Event Type',
  '請選擇活動類型': 'Select event type',
  '活動標題': 'Event Title',
  '請輸入活動標題': 'Enter event title',
  '請選擇開始時間': 'Select start time',
  '請選擇結束時間': 'Select end time',
  '選擇年月': 'Select Year & Month',
  '請輸入歷史及介紹': 'Enter history and introduction',
  '活動封面': 'Event Cover Image',
  '確認發佈活動': 'Confirm Post Event',
  '開始時間不能大於結束時間': 'Start time cannot be later than end time',
  '開始時間或結束時間格式錯誤': 'Invalid start or end time format',

  /// 發佈交通
  '交通名稱': 'Transportation Name',
  '請輸入交通名稱': 'Enter transportation name',
  '請輸入介紹內容': 'Enter introduction',
  '交通封面': 'Transportation Cover Image',
  '確認發佈交通': 'Confirm Post Transportation',
  '確定要刪除這條內容嗎？': 'Delete this content?',
  '已刪除': 'Deleted',

  /// 邀請
  '複製成功': 'Copied',
  '我的邀請碼': 'My Invitation Code',
  '複製': 'Copy',

  /// 商家發布
  '商家發布': 'Business Post',
  '請選擇商家類型': 'Select business type',
  '請選擇分類': 'Select category',
  '請輸入名稱': 'Enter name',
  '名稱': 'Name',
  '請輸入營業時間': 'Enter business hours',
  '請輸入餐廳可容納人數': 'Enter restaurant capacity',
  '請輸入景點開放時間': 'Enter attraction opening hours',
  '景點開放時間': 'Attraction Opening Hours',
  '請輸入價格': 'Enter price',
  '價格': 'Price',
  '請輸入其他聯係方式': 'Enter other contact info',
  '其他聯係方式': 'Other Contact Info',
  '請輸入電話': 'Enter phone number',
  '請輸入網址': 'Enter website',
  '請輸入商家介紹': 'Enter business introduction',
  '商家介紹': 'Business Introduction',
  '確認發佈商家': 'Confirm Post Business',

  /// 預約導遊
  '預約行程': 'Booking',
  '預約導遊信息': 'Guide Booking Details',
  '預約城市': 'Booking City',
  '請選擇預約城市': 'Select booking city',
  '預計到達時間': 'Estimated Arrival Time',
  '請選擇預計到達時間': 'Select estimated arrival time',
  '人數': 'Number of People',
  '請輸入人數': 'Enter number of people',
  '行程/備註說明': 'Itinerary/Notes',
  '請輸入行程/備註說明': 'Enter itinerary/notes',
  '聯繫人': 'Contact Person',
  '請輸入聯繫人姓名': 'Enter contact person name',
  '聯繫人郵箱': 'Contact Person Email',
  '請輸入聯繫人郵箱': 'Enter contact person email',
  '請輸入手機號碼': 'Enter mobile number',
  '請輸入其他聯繫方式,例如:微信:1231231': 'Enter other contact info, e.g., WeChat:1231231',
  '我要預約': 'Book Now',
  '預約成功，請等待導遊確認~': 'Booking successful, waiting for guide confirmation~',
  '確認修改': 'Confirm Changes',

  /// 商家預約
  '預約餐廳信息': 'Restaurant Booking Details',
  '預約購物信息': 'Shopping Booking Details',
  '預約住宿信息': 'Accommodation Booking Details',
  '預約票務信息': 'Ticket Booking Details',
  '預約景點信息': 'Attraction Booking Details',
  '住宿預約': 'Hotel Booking',
  '入住時間': 'Check-in Time',
  '請選擇入住時間': 'Select check-in time',
  '離店時間': 'Check-out Time',
  '請選擇離店時間': 'Select check-out time',
  '入住人數': 'Number of Guests',
  '請輸入入住人數': 'Enter number of guests',
  '房間數': 'Number of Rooms',
  '請輸入房間數': 'Enter number of rooms',
  '其他要求': 'Other Requirements',
  '請輸入其他要求': 'Enter other requirements',
  '門票類型': 'Ticket Type',
  '請輸入門票類型': 'Enter ticket type',
  '客戶名單': 'Customer List',
  '選擇文件': 'Select File',
  '立即預約': 'Book Now',
  '預約成功，請等待商家確認~': 'Booking successful, waiting for business confirmation~',
  '文件大小不能超過10MB': 'File size must not exceed 10MB',
  '文件選擇成功': 'File selected successfully',

  /// 預約詳情
  '查看行程': 'View trip',
  '查看預約': 'View booking',
  '預約時間': 'Booking Time',
  '確認預約': 'Confirm Booking',
  '完成預約': 'Complete Booking',
  '行程/備注說明': 'Itinerary/Notes',
  '預約已確認': 'Booking Confirmed',
  '商家預約詳情': 'Business Booking Details',
  '待確認': 'Pending',
  '已完成': 'Completed',
  '新預約': 'New Booking',
  '已確認': 'Confirmed',

  /// 我的發佈
  '我的發佈': 'My Posts',
  '發佈': 'Post',
  '發佈時間': 'Post Time',
  '審核駁回': 'Rejected',
  '駁回原因': 'Rejection Reason',
  '發布景點': 'Post Attraction',
  '發布資訊': 'Post News',
  '發布交通': 'Post Transportation',
  '發布設施': 'Post Facility',
  '發布活動': 'Post Event',

  /// 發布城市頁面
  '發布城市': 'Post City',
  '城市名稱（中文名）': 'City Name (Chinese)',
  '城市名稱（英文名）': 'City Name (English)',
  '請輸入城市中文名': 'Enter city name in Chinese',
  '請輸入城市英文名': 'Enter city name in English',
  '城市地理區塊': 'Geographic Region',
  '城市所屬地區': 'Region',
  '城市所屬國家': 'Country',
  '請選擇所在大洲': 'Select continent',
  '請選擇城市所屬地區': 'Select region',
  '請選擇城市所屬國家': 'Select country',
  '是否是首都城市': 'Is Capital City',
  '貨幣': 'Currency',
  '請輸入貨幣': 'Enter currency',
  '官方語言': 'Official Language(s)',
  '請輸入官方語言': 'Enter official language(s)',
  '人口數量': 'Population',
  '請輸入人口數量': 'Enter population',
  '萬': '10k',
  '種族': 'Ethnicity',
  '請輸入種族': 'Enter ethnicity',
  '請輸入城市概覽': 'Enter city overview',
  '請輸入城市歷史': 'Enter city history',
  '城市封面': 'City Cover Image',
  '只能上傳JPG/PNG文件，且不超過500KB': 'Only JPG/PNG files under 500KB',
  '確認發布城市': 'Confirm Post City',
  '確定要刪除這個城市嗎？': 'Delete this city?',

  /// 會籍中心
  '積分兌換': 'Redeem with Points',
  '付費購買': 'Purchase',
  '月': 'Month',
  '年': 'Year',
  '日': 'Day',
  '全部數據': 'All Data',
  '取消預約': 'Cancel Booking',
  '刪除預約': 'Delete Booking',
  '確定要取消此預約嗎？': 'Cancel this booking?',
  '確定要刪除此預約嗎？': 'Delete this booking?',
  '取消成功': 'Cancelled Successfully',
  '拒絕預約': 'Reject Booking',
  '拒絕理由': 'Rejection Reason',
  '請輸入拒絕理由': 'Enter rejection reason',
  '已拒絕': 'Rejected',
  '點擊按鈕即同意': 'Clicking the button means you agree to',
  '《VIP會員訂閲服務協議》': 'the VIP Membership Subscription Service Agreement',
  '《VIP會員服務協議》': 'the VIP Membership Service Agreement',
  '立即訂閱': 'Subscribe Now',
  '會員已過期': 'Membership Expired',
  '會員有效期': 'Membership Validity',
  '圖片上傳失敗': 'Image upload failed',

  /// 城市選擇
  '選擇城市': 'Select City',

  /// 時間格式
  '剛剛': 'Just now',
  '分鐘前': 'minutes ago',
  '小時前': 'hours ago',
  '昨天': 'Yesterday',
  '天前': 'days ago',
  '上週': 'Last week',
  '週前': 'weeks ago',
  '上個月': 'Last month',

  '企業信息:': 'Company Info:',
  '企業詳情': 'Company Details',
  '店鋪列表': 'Store List',
  'EMAIL': 'EMAIL',
  '公司網站': 'Company Website',
  '關注了您的店舖': 'followed your store',
  '評分': 'Rating',

  /// 搜索功能
  '未找到相關城市': 'No related cities found',
  '未找到相關內容': 'No related content found',

  /// 支付相關
  '支付成功': 'Payment successful',
  '支付失敗': 'Payment failed',
  '支付方式無效': 'Invalid payment method',
  '支付處理中': 'Payment processing',
  '支付被取消': 'Payment cancelled',
  '支付超時': 'Payment timeout',
  '網絡錯誤，請檢查網絡連接': 'Network error, please check connection',
  '支付系統錯誤': 'Payment system error',
  '未知錯誤': 'Unknown error',

  '請輸入完整的電話號碼(帶區號)': 'Enter full phone number (with area code)',
  '知道了': 'Got it',
  '權限不足': 'Insufficient permissions',
  '您的會員已過期，想繼續使用全部功能，請延長會員會籍':
      'Your membership has expired. To continue using all features, please extend it.',
  '店铺管理': 'Store Management',
  '小貼士': 'Tips',
  '請輸入城市/導遊/內容': 'Enter city/guide/content',
  '1月': 'Jan',
  '2月': 'Feb',
  '3月': 'Mar',
  '4月': 'Apr',
  '5月': 'May',
  '6月': 'Jun',
  '7月': 'Jul',
  '8月': 'Aug',
  '9月': 'Sep',
  '10月': 'Oct',
  '11月': 'Nov',
  '12月': 'Dec',
  '註銷賬號': 'Delete Account',
  '註銷賬號會將您的數據刪除並且無法找回，確定要註銷賬號嗎？':
      'Deleting your account will erase your data irrecoverably. Are you sure?',
  '（此內容不會公開，僅供內部審核）': '(This content is not public, for internal review only)',
  '請輸入包含國際區號的電話號碼：示例+4912345678':
      'Enter phone number with country code: e.g., +4912345678',
  '分享失敗': 'Share failed',
  '正在生成分享圖片...': 'Generating share image...',
  '生成圖片失敗': 'Failed to generate image',
  '生成圖片失敗，請稍後再試': 'Image generation failed, please try again later',
  '分享預覽': 'Share Preview',
  '分享文件不存在': 'Share file does not exist',
  '分享文件無效': 'Share file is invalid',
  '探索世界，發現精彩旅程': 'Explore the world, discover wonderful journeys',
  '邀請鏈接不存在': 'Invitation link does not exist',
  '邀請您加入 LUMOGUIDE': 'Inviting you to join LUMOGUIDE',
  '邀請碼：': 'Invitation Code:',
  '微信/Wechat': 'WeChat',
  'WhatsApp': 'WhatsApp',
  'Line': 'Line',
  '其他': 'Other',
  '暫無紀錄': 'No records',
  '延長會籍': 'Renew',
  '僅允許上傳擁有版權或自拍的圖片，違法圖片後果自負':
      'Only allow uploading images with copyright or selfies. Violating the law will result in legal consequences.',
  '清除緩存成功': 'Clear cache successfully',
  '城市攻略': 'City Strategy',
  '免費試⽤期間只能添加一個店铺，想繼續使用全部功能，請延長會員會籍':
      'During the free trial, only one shop can be added. To access all features, please extend your membership.',
  '獲取導遊信息失敗': 'Failed to get guide info',
  '獲取企業信息失敗': 'Failed to get company info',
  '升級成為 LuMo Guide 或合作商家，即可查看更多城市詳情內容':
      'Upgrade to LuMo Guide or a partner merchant to view more city details.',
  '請輸入微信/Wechat': 'Please enter WeChat',
};
