# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:android)

platform :android do
  desc "上传firim"
  lane :fir do
    sh("flutter", "build", "apk", "--release")
    firim(
      apk:"../build/app/outputs/apk/release/app-release.apk",
      platform:"android",
      firim_api_token: "87acf8077809886bc01976655cc70eb8", 
      firim_api_url: "https://api.appmeta.cn/",
      app_changelog: "Release",
      gradle_file: "./app/build.gradle",
      app_name:"LUMOGUIDE"
    )
  end

end